name: Lint files on push

on:
  push:
    branches: [master, fix/*, chore/*, feat/*]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "19"
      - name: Installing node_modules
        run: npm install
      - name: Running Prettier
        run: npm run format
      - name: Running ESLint
        run: npm run lint:fix
      - name: Build the app
        run: npm run build
